# == This file defines the page layouts for new pages.
#
# For further information please see http://guides.alchemy-cms.com/stable/page_layouts.html

- name: index
  unique: true
  elements: [article]
  autogenerate: [article]
- name: posts
  unique: true
  elements: [article]
- name: post
  unique: false
  elements: [post_details, band_set]
  autogenerate: [post_details, band_set]
